services:
  bot-dev:
    image: "bot"
    container_name: "bot-dev"
    stop_signal: SIGINT
    build:
      context: ./
      dockerfile: ./Dockerfile
    working_dir: "/usr/src/app/bot"
    volumes:
      - /usr/src/app/bot
    command: python3 -m bot
    restart: always
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  pg_database:
    image: postgres:13-alpine
    container_name: "pg_database"
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  redis-dev:
    image: redis:6.2-alpine
    container_name: "redis-dev"
    ports:
      - "6388:6388"
    restart: always
    command: /bin/sh -c "redis-server --port $$REDISPORT --save 20 1 --loglevel warning --requirepass $$REDISPASSWORD"
    env_file:
      - .env
    volumes:
      - cache:/data

volumes:
  cache: {}
  pgdata: { }
