"""empty message

Revision ID: 8e8ef0ee9e4a
Revises: a43d69c5583f
Create Date: 2024-07-11 14:30:50.972659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e8ef0ee9e4a'
down_revision: Union[str, None] = 'a43d69c5583f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'answer',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'answer',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
