"""empty message

Revision ID: 9d1a9cbecd0b
Revises: 
Create Date: 2024-07-10 10:05:48.112832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d1a9cbecd0b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exam', sa.String(length=20), nullable=False),
    sa.Column('chapter', sa.String(length=20), nullable=False),
    sa.Column('under_chapter', sa.String(length=70), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('answer_mode', sa.String(length=10), nullable=False),
    sa.Column('answers', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('addition', sa.Text(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('is_subscribe', sa.Boolean(), nullable=False),
    sa.Column('day_end_subscribe', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('task')
    # ### end Alembic commands ###
