"""empty message

Revision ID: b9d382692e3e
Revises: 1f24c123afa8
Create Date: 2024-07-11 14:40:22.009264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9d382692e3e'
down_revision: Union[str, None] = '1f24c123afa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('block', sa.Column('callback_button_id', sa.Text(), nullable=True))
    op.drop_column('media_block', 'callback_button_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_block', sa.Column('callback_button_id', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('block', 'callback_button_id')
    # ### end Alembic commands ###
