"""empty message

Revision ID: c16f616a2357
Revises: 53cf62df6c50
Create Date: 2024-07-11 15:19:03.757367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c16f616a2357'
down_revision: Union[str, None] = '53cf62df6c50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('is_visible', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'is_visible')
    # ### end Alembic commands ###
