"""empty message

Revision ID: ed068edfce21
Revises: 8e8ef0ee9e4a
Create Date: 2024-07-11 14:31:58.602906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed068edfce21'
down_revision: Union[str, None] = '8e8ef0ee9e4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'answers',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('task', 'answer',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'answer',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('task', 'answers',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
